In [15]:
import numpy as np 
import pandas as pd 

In [16]:
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

#### Using matrix form of y_cap = XB 
and then differentiating it with respect to B we find formula for B which is:
##### B = (X_tranpose.X)-1 * (X_transpose.Y)

In [49]:
class MyMultiLR:
    def __init__(self):
        self.offset = []
        self.weights = []
    def fit(self, x, y):
        # we insert rows of 1 in our matrix for offset
        x=np.insert(x,0,1,axis=1)
        x_t = np.transpose(x)
        beta = np.linalg.inv(np.dot(x_t,x)).dot(x_t).dot(y)
        self.offset = beta[0]
        self.weights = beta[1:]
    def predict(self,x_test):
        return np.dot(x_test,self.weights).ravel() + self.offset
        

In [50]:
X, y = make_regression(n_samples=300, n_features=4, random_state=42)

In [51]:
x_train, x_test, y_train, y_test = train_test_split(X, y , random_state=42, test_size=0.2)

In [52]:
mr = MyMultiLR()

mr.fit(x_train, y_train)

y_pred = mr.predict(x_test)

In [54]:
y_pred

array([   4.66752313,  221.48647963,  109.19062881,  -88.81478838,
       -121.73528738, -133.84495044,  -88.28173699,  175.10569182,
        225.72610851,  123.67119932,   12.92759674,  -16.34294488,
         -5.06459018, -202.46144638,  324.53811428, -102.46894393,
        271.64296569,   33.11252223,   45.96248574,  249.19103813,
        101.7056395 ,   11.4303826 , -205.71102754,  113.41865073,
         14.55126449,   78.56537636, -270.57521798, -113.64962182,
         13.43795988, -186.96569501, -129.15403662,  160.06944646,
        -67.92884023,  118.84142873,   -5.57627421,  -13.68936359,
        -80.71192524,  230.55620732,  156.06214586,  105.65943075,
         89.12693461,  -15.81914737, -202.8440266 , -187.74310272,
       -182.49701207, -219.91606603,  -58.07931654,   -1.55874137,
       -174.85082597,  151.61404922,  -66.56769517,   11.75757669,
        -72.65750165,   51.41572961,  173.32616352,   -8.66546475,
        177.82442125,  180.55812192,  103.56226658,  -16.22711

In [55]:
lr = LinearRegression()

lr.fit(x_train , y_train)

y_pred_2 = lr.predict(x_test)

In [56]:
y_pred_2

array([   4.66752313,  221.48647963,  109.19062881,  -88.81478838,
       -121.73528738, -133.84495044,  -88.28173699,  175.10569182,
        225.72610851,  123.67119932,   12.92759674,  -16.34294488,
         -5.06459018, -202.46144638,  324.53811428, -102.46894393,
        271.64296569,   33.11252223,   45.96248574,  249.19103813,
        101.7056395 ,   11.4303826 , -205.71102754,  113.41865073,
         14.55126449,   78.56537636, -270.57521798, -113.64962182,
         13.43795988, -186.96569501, -129.15403662,  160.06944646,
        -67.92884023,  118.84142873,   -5.57627421,  -13.68936359,
        -80.71192524,  230.55620732,  156.06214586,  105.65943075,
         89.12693461,  -15.81914737, -202.8440266 , -187.74310272,
       -182.49701207, -219.91606603,  -58.07931654,   -1.55874137,
       -174.85082597,  151.61404922,  -66.56769517,   11.75757669,
        -72.65750165,   51.41572961,  173.32616352,   -8.66546475,
        177.82442125,  180.55812192,  103.56226658,  -16.22711

In [57]:
lr.coef_, lr.intercept_

(array([ 4.34125329, 95.14033422, 63.31513756, 60.16118201]),
 1.4210854715202004e-14)

In [58]:
mr.weights , mr.offset

(array([ 4.34125329, 95.14033422, 63.31513756, 60.16118201]),
 2.220446049250313e-15)